[package]
name = "jsphere_vv8_log"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
lazy-regex.workspace = true
rayon.workspace = true
shame.workspace = true

[dev-dependencies]
rand.workspace = true
